### ISSUE TITLE
HAL_Delay(); problem

### ISSUE THREAD

**Issue by gsaikiran29** [darkspr1te/stm32f407_vet_bootloader#2]
Hello, @darkspr1te 
In my 2nd Application HAL_Delay is not working?
If i keep HAL_Delay() in simple buzzer high low code, it will do buzzer high and hangs there itself. what would be the problem?

**Comment by darkspr1te** [comment]
is it being compiled via arduino enviroment ? or another ? what stm subsystem are you using ? stm32cube/stmduino official /roger clark stmduino / platformio with one of the prior build subsystem ? did you try vanilia delay(); (little tip, in platformio you can swap between the three if you keep code base simple enough , handy when building using other sources of code)
